import express from "express";
import { createPost } from "../controller/post/post.create.js";
import { findPost } from "../controller/post/post.find.js";
import { authMiddleware } from "../middleware/auth-middleware.js";
import { findUserPost } from "../controller/post/post.user.js";
import { toggleLike } from "../controller/post/post.like.js";
import { findUserPosts } from "../controller/post/findUser.post.js";
import { findEachPost } from "../controller/post/eachPost.js";
import { del } from "../controller/post/delete.post.js";
const postRouter = express.Router();
postRouter.post("/create", authMiddleware, createPost);
postRouter.get("/posts", authMiddleware, findPost);
postRouter.get("/userPosts", authMiddleware, findUserPost);
postRouter.post("/postLike/:postId", authMiddleware, toggleLike);
postRouter.get("/postUser/:userId", authMiddleware, findUserPosts);
postRouter.get("/userPost/:postId", authMiddleware, findEachPost);
postRouter.delete("/deletePost/:postId", authMiddleware, del);
export default postRouter;
